### ISSUE TITLE
Add BLE (Bluetooth Low Energy) to acquire information from Micro:bit wirelessly

### ISSUE THREAD

**Issue by lyshie** [MrYsLab/s2m#12]
We could use BluetoothLE to acquire information from Micro:bit wirelessly.

1. pygatt is suitable for this purpose
https://pypi.python.org/pypi/pygatt
2. some useful references about Micro:bit and BLE
http://class.tn.edu.tw/modules/tad_web/news.php?WebID=1384&NewsID=10851

**Comment by MrYsLab** [comment]
BLE is currently not supported by micropython on the micro:bit http://microbit-micropython.readthedocs.io/en/latest/ble.html, so I do not plan to support BLE at this time.

This article may provide what you are looking for: http://www.picaxe.com/BBC-microbit

I am starting to look at the Radio feature: http://microbit-micropython.readthedocs.io/en/latest/tutorials/radio.html?highlight=radio

My intent is to use Scratch to drive a robot vehicle by attaching one micro:bit to USB and have another micro:bit as the controller on the vehicle. This will provide wireless robot control. This is planned for the future, but I don't have a schedule in place yet to implement this.

**Comment by lyshie** [comment]
Here is my `BluetoothLE` test result and source code
1. [YouTube - Scratch controller with Micro:bit over BLE](https://youtu.be/kHZFJNNkeDY)
2. https://github.com/lyshie/scratch2-microbit/blob/master/microbit_ext_ble.py

There is no micropython code to run.  Without using S2Bot or BLED112 dongle (BLE to UART), we could use `pygatt` and `node-bbc-microbit-v0.1.0.hex` to provide another way to bridge Scratch2 and Micro:bit together.

- https://github.com/sandeepmistry/node-bbc-microbit/

**Comment by MrYsLab** [comment]
I may not be understanding things too well here. It appears your code is running without the node-bbc-microbit hex image. If that is correct, why is node-bbc-microbit needed? It looks like everything could be controlled and monitored with pygatt.

**Comment by MrYsLab** [comment]
I spent a little more time looking into this. I don't think it is correct that simply using pygatt and node-bbc-microibit-v0.1.0.hex will work without some sort of BLE dongle for computers that are not Bluetooth enabled. If you look at https://www.npmjs.com/package/bbc-microbit-io, the prerequisites state that a BLE enabled computer required.

If I can find my BLE dongle, I will download your project and try it out. I am still not sure if I want to tackle this because it is my understanding that in a classroom situation, with many computers operating at once, Bluetooth connections interfere with each other making communication difficult if not impossible.

In addition, the cost for a quality BLE dongle is almost the same as the cost of a micro:bit here in the U.S. This points me back to trying to use the micro:bit Radio feature. I don't know if Radio has less interference issues, but since it is channelized and the channels can be selected, it may be a better solution (or maybe not).

So I am not yet convinced I want to go down the BLE (or Radio) route yet, but am willing to spend a little more time looking at it.

**Comment by lyshie** [comment]
Thanks, you are right and I tested it on my notebook. Although modern notebooks and handheld devices has BluetoothLE built in, many computers in a classroom still need BLE dongles.
