### ISSUE TITLE
Any plan to support Scratch 1.4?

### ISSUE THREAD

**Issue by champierre** [MrYsLab/s2m#35]
In some schools in Japan, they allow their students to use Scratch 1.4 only. Do you have a plan to support Scratch 1.4?
If yes, I can try and open PR.

I think I can use remote sensing protocol in a similar way I did in sctatch2mcpi(https://github.com/scratch2mcpi/scratch2mcpi).

**Comment by MrYsLab** [comment]
Hi @champierre .
I understand why it may be difficult for a school to move to another platform, but unfortunately, I have not implemented an extension for Scratch 1.4. It is very different from Scratch 2 and would not be easy for me to do.  Also, it is my understanding that it only supports reporting through the use of broadcasts, but does not have a mechanism to support sending commands to an external device. Therefore, I will not be able to help much with this. 
If you have access to twitter, you might want to contact Simon Walters https://twitter.com/cymplecy who has implemented supporting Raspberry Pi GPIO for Scratch 1.4.

I am going to close this issue, but please feel free to leave additional comments here. If  you feel I can be of help in some way, let me know and I will try my best to support you.

**Comment by sobreira** [comment]
Hi @champierre <https://github.com/champierre>

Sorry Alan - not sure if this is the formal way for comunication.....

Have you heard about S4A - http://s4a.cat/
S4A is also used in some public schools in Brazil, despite I promote the
Alan alternative which is much better....
Since 2012 we migrated all workshops and developments for S2a-fm or S2aio.

Scratch1.4 is outdated and lack good functions compared to Scratch 2.0.

Edson
https://www.hackeduca.com.br


Em qui, 24 de jan de 2019 às 13:12, Alan Yorinks <notifications@github.com>
escreveu:

**Comment by MrYsLab** [comment]
Hi @sobreira . S4A does work with Arduino but not micro:bit. It is very old and I don't think it has been updated in a very long while.

**Comment by sobreira** [comment]
You´re right, actually my fault
I misread that this is a s2m and not s2aio.

Em qui, 24 de jan de 2019 às 14:20, Alan Yorinks <notifications@github.com>
escreveu:
